/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scientific_Calculate;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ok Computers
 */
public class Scientific_Cal extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double result;
    String operations;
    private Object math;
    
    public Scientific_Cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtxtDisplay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnminus = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnmulti = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtndivide = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtndecimal = new javax.swing.JButton();
        jbtnplusminus = new javax.swing.JButton();
        jbtnisequals = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnV = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtnsin = new javax.swing.JButton();
        jbtnsinh = new javax.swing.JButton();
        jbtnLog = new javax.swing.JButton();
        jbtncos = new javax.swing.JButton();
        jbtncoh = new javax.swing.JButton();
        jbtnCbr = new javax.swing.JButton();
        jbtntan = new javax.swing.JButton();
        jbtntanh = new javax.swing.JButton();
        jbtnxy = new javax.swing.JButton();
        jbtnhexa = new javax.swing.JButton();
        jbtnround = new javax.swing.JButton();
        jbtnxy2 = new javax.swing.JButton();
        jbtnpi = new javax.swing.JButton();
        jbtnBinary = new javax.swing.JButton();
        jbtnxy3 = new javax.swing.JButton();
        jbtnmod = new javax.swing.JButton();
        jbtnlnx = new javax.swing.JButton();
        jbtnF = new javax.swing.JButton();
        jbtnbCelsius = new javax.swing.JButton();
        jbtnocta = new javax.swing.JButton();
        jCDistance = new javax.swing.JComboBox<>();
        jtxtEnter1 = new javax.swing.JTextField();
        jtxtEnter2 = new javax.swing.JTextField();
        j1b1Display1 = new javax.swing.JTextField();
        j1b1Display3 = new javax.swing.JTextField();
        j1b1Display2 = new javax.swing.JTextField();
        j1b1Result = new javax.swing.JTextField();
        jbtnconverter = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jtxtX = new javax.swing.JTextField();
        jbtncm = new javax.swing.JButton();
        jbtnm = new javax.swing.JButton();
        jbtnkg = new javax.swing.JButton();
        jbtnlitre = new javax.swing.JButton();
        jCzakat = new javax.swing.JComboBox<>();
        jtxtEnterZ = new javax.swing.JTextField();
        j2b2Result = new javax.swing.JTextField();
        jbtnzakatconverter = new javax.swing.JButton();
        jbtnzakatReset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jtxtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyTyped(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnminus.setText("-");
        jbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminusActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnmulti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnmulti.setText("*");
        jbtnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtndivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtndivide.setText("/");
        jbtndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivideActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtndecimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndecimal.setText(".");
        jbtndecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndecimalActionPerformed(evt);
            }
        });

        jbtnplusminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnplusminus.setText("±");
        jbtnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusminusActionPerformed(evt);
            }
        });

        jbtnisequals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnisequals.setText("=");
        jbtnisequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnisequalsActionPerformed(evt);
            }
        });

        jbtnBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnBackspace.setText("←");
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtnV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnV.setText("√");
        jbtnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVActionPerformed(evt);
            }
        });

        jbtnplus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });

        jbtnsin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnsin.setText("Sin");
        jbtnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinActionPerformed(evt);
            }
        });

        jbtnsinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnsinh.setText("Sinh");
        jbtnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinhActionPerformed(evt);
            }
        });

        jbtnLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLog.setText("Log");
        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogActionPerformed(evt);
            }
        });

        jbtncos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtncos.setText("Cos");
        jbtncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncosActionPerformed(evt);
            }
        });

        jbtncoh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtncoh.setText("Cosh");
        jbtncoh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncohActionPerformed(evt);
            }
        });

        jbtnCbr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCbr.setText("Cbr");
        jbtnCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCbrActionPerformed(evt);
            }
        });

        jbtntan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtntan.setText("Tan");
        jbtntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanActionPerformed(evt);
            }
        });

        jbtntanh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtntanh.setText("Tanh");
        jbtntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanhActionPerformed(evt);
            }
        });

        jbtnxy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnxy.setText("x^y");
        jbtnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxyActionPerformed(evt);
            }
        });

        jbtnhexa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnhexa.setText("Hexa");
        jbtnhexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhexaActionPerformed(evt);
            }
        });

        jbtnround.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jbtnround.setText("Rund");
        jbtnround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnroundActionPerformed(evt);
            }
        });

        jbtnxy2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnxy2.setText("x^2");
        jbtnxy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxy2ActionPerformed(evt);
            }
        });

        jbtnpi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnpi.setText("pi");
        jbtnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpiActionPerformed(evt);
            }
        });

        jbtnBinary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBinary.setText("Bin");
        jbtnBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBinaryActionPerformed(evt);
            }
        });

        jbtnxy3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnxy3.setText("x^3");
        jbtnxy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxy3ActionPerformed(evt);
            }
        });

        jbtnmod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnmod.setText("Mod");
        jbtnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodActionPerformed(evt);
            }
        });

        jbtnlnx.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnlnx.setText("lnx");
        jbtnlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlnxActionPerformed(evt);
            }
        });

        jbtnF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnF.setText("Fahrenheit");
        jbtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFActionPerformed(evt);
            }
        });

        jbtnbCelsius.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtnbCelsius.setText("Celsius");
        jbtnbCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbCelsiusActionPerformed(evt);
            }
        });

        jbtnocta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnocta.setText("octa");
        jbtnocta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoctaActionPerformed(evt);
            }
        });

        jCDistance.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jCDistance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "Speed", "Distance", "Time", "Work", "Acceleration", "Force", "Power", "Momentum" }));
        jCDistance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDistanceActionPerformed(evt);
            }
        });

        jtxtEnter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEnter1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEnter1ActionPerformed(evt);
            }
        });

        jtxtEnter2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEnter2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEnter2ActionPerformed(evt);
            }
        });

        j1b1Display1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j1b1Display1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1b1Display1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1b1Display1ActionPerformed(evt);
            }
        });

        j1b1Display3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j1b1Display3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1b1Display3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1b1Display3ActionPerformed(evt);
            }
        });

        j1b1Display2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j1b1Display2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1b1Display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1b1Display2ActionPerformed(evt);
            }
        });

        j1b1Result.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j1b1Result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1b1Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1b1ResultActionPerformed(evt);
            }
        });

        jbtnconverter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnconverter.setText("Convert");
        jbtnconverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnconverterActionPerformed(evt);
            }
        });

        jbtnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnreset.setLabel("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jtxtX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtX.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtncm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtncm.setText("cm");
        jbtncm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncmActionPerformed(evt);
            }
        });

        jbtnm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnm.setText("m");
        jbtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmActionPerformed(evt);
            }
        });

        jbtnkg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnkg.setText("kg");
        jbtnkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnkgActionPerformed(evt);
            }
        });

        jbtnlitre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnlitre.setText("Litr");
        jbtnlitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlitreActionPerformed(evt);
            }
        });

        jCzakat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCzakat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "Net Worth", "Gold", "Silver" }));
        jCzakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCzakatActionPerformed(evt);
            }
        });

        jtxtEnterZ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEnterZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        j2b2Result.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j2b2Result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2b2Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2b2ResultActionPerformed(evt);
            }
        });

        jbtnzakatconverter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnzakatconverter.setText("Convert");
        jbtnzakatconverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnzakatconverterActionPerformed(evt);
            }
        });

        jbtnzakatReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnzakatReset.setText("Reset");
        jbtnzakatReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnzakatResetActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Physics Formulas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Zakat");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtntan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtntanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                                    .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtnV, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jtxtDisplay))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnsinh))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtncos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtncoh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnxy2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnround, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtndecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnisequals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnxy3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnlnx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnbCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnocta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtncm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnkg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnlitre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtEnter2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtxtEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(jbtnconverter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(17, 17, 17))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j1b1Display1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(j1b1Display2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                            .addComponent(jtxtX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(j1b1Display3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(j1b1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(150, 150, 150)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCzakat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnzakatconverter, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnzakatReset, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtxtEnterZ, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(j2b2Result, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCDistance)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtncoh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtncos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnxy2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnhexa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnround, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtntan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtntanh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jbtnbCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtndecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnisequals, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnxy3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnocta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtEnter2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1b1Display1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1b1Display3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1b1Display2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(j1b1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnconverter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtncm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnkg, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnlitre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jCzakat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jtxtEnterZ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(j2b2Result, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnzakatReset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnzakatconverter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(655, 600);
        jtxtDisplay.setSize(625, 52);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminusActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("-");
    }//GEN-LAST:event_jbtnminusActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn7.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn8.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn9.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("*");
    }//GEN-LAST:event_jbtnmultiActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn1.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn2.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn3.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivideActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("/");
    }//GEN-LAST:event_jbtndivideActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        
        String iNum = jtxtDisplay.getText() + jbtn0.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtndecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndecimalActionPerformed
        
        if (!jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtndecimal.getText());
        }
    }//GEN-LAST:event_jbtndecimalActionPerformed

    private void jbtnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusminusActionPerformed
        
        double ops = Double.parseDouble(jtxtDisplay.getText());
        ops = ops *(-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnplusminusActionPerformed

    private void jbtnisequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnisequalsActionPerformed
        String answer;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        if (operations == "+")
        {
         result = firstnum + secondnum;
         answer = String.format("%.0f",result);
         jtxtDisplay.setText(answer);
        }
        else if (operations == "-")
        {
         result = firstnum - secondnum;
         answer = String.format("%.0f",result);
         jtxtDisplay.setText(answer);
        }
        else if (operations == "*")
        {
         result = firstnum * secondnum;
         answer = String.format("%.0f",result);
         jtxtDisplay.setText(answer);
        }
        else if (operations == "/")
        {
         result = firstnum / secondnum;
         answer = String.format("%.0f",result);
         jtxtDisplay.setText(answer);
        }
        else if (operations == "%")
        {
         result = firstnum % secondnum;
         answer = String.format("%.0f",result);
         jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jbtnisequalsActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(295, 600);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         this.setResizable(true);
        this.setSize(295, 600);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String bsp = null;
        if(jtxtDisplay.getText().length() > 0 )
        {
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
            bsp = strB.toString();
            jtxtDisplay.setText(bsp);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sqrt(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnVActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("+");
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sin(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnsinActionPerformed

    private void jbtnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinhActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sinh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnsinhActionPerformed

    private void jbtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.log(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnLogActionPerformed

    private void jbtncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncosActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cos(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncosActionPerformed

    private void jbtncohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncohActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cosh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncohActionPerformed

    private void jbtnCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCbrActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops =Math.cbrt(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnCbrActionPerformed

    private void jbtntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tan(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtntanActionPerformed

    private void jbtntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanhActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tanh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtntanhActionPerformed

    private void jbtnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxyActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops =Math.pow(ops, ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnxyActionPerformed

    private void jbtnhexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhexaActionPerformed
         
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString(a,16));
    }//GEN-LAST:event_jbtnhexaActionPerformed

    private void jbtnroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnroundActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.round(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnroundActionPerformed

    private void jbtnxy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxy2ActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops * ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnxy2ActionPerformed

    private void jbtnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpiActionPerformed
        
        double ops;
        ops = (3.1415926535897932384626433832795);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnpiActionPerformed

    private void jbtnBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBinaryActionPerformed
        
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString(a,2));
    }//GEN-LAST:event_jbtnBinaryActionPerformed

    private void jbtnxy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxy3ActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops * ops * ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnxy3ActionPerformed

    private void jtxtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyTyped
        
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDisplayKeyTyped

    private void jbtnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmodActionPerformed

    private void jbtnlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlnxActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.log10(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnlnxActionPerformed

    private void jbtnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFActionPerformed
        
        int b = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString((int) (32 + 1.8 * b)));
    }//GEN-LAST:event_jbtnFActionPerformed

    private void jbtnbCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbCelsiusActionPerformed
        
        int c = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString((int) (c-32)*5/9));
    }//GEN-LAST:event_jbtnbCelsiusActionPerformed

    private void jbtnoctaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoctaActionPerformed
        
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString(a,8));
    }//GEN-LAST:event_jbtnoctaActionPerformed

    private void jCDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDistanceActionPerformed

    private void jtxtEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEnter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEnter1ActionPerformed

    private void jtxtEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEnter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEnter2ActionPerformed

    private void j1b1Display1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1b1Display1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1b1Display1ActionPerformed

    private void j1b1Display3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1b1Display3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1b1Display3ActionPerformed

    private void j1b1ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1b1ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1b1ResultActionPerformed

    private void jbtnconverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnconverterActionPerformed
        if ((jtxtEnter1.getText().equals(""))||(jtxtEnter2.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"You must enter value to compute",
                    "DST System", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if(jCDistance.getSelectedItem().equals("Distance"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //distance Formula = speed * time
            j1b1Display1.setText("Distance = ");
            j1b1Display2.setText("Speed ");
            jtxtX.setText("X");
            j1b1Display3.setText("Time");
            dst3 = dst1 * dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Speed"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Speed Formula = Distance / time
            j1b1Display1.setText("Speed = ");
            j1b1Display2.setText("Distance ");
            jtxtX.setText("/");
            j1b1Display3.setText("Time");
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Time"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Time Formula = Distance / Speed
            j1b1Display1.setText("Time = ");
            j1b1Display2.setText("Distance ");
            jtxtX.setText("/");
            j1b1Display3.setText("Speed");
            dst3 = (dst1 * dst2) / dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Work"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Work Formula = Force * Displacement
            j1b1Display1.setText("Work = ");
            j1b1Display2.setText("Force ");
            jtxtX.setText("X");
            j1b1Display3.setText("Displacement");
            dst3 = dst1 * dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Acceleration"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Acceleration Formula = velocity / Time
            j1b1Display1.setText("Acceleration = ");
            j1b1Display2.setText("velocity ");
            jtxtX.setText("/");
            j1b1Display3.setText("Time");
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Force"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Force Formula = Mass * Acceleration
            j1b1Display1.setText("Force = ");
            j1b1Display2.setText("Mass ");
            jtxtX.setText("X");
            j1b1Display3.setText("Acceleration");
            dst3 = dst1 * dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Power"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Power Formula = Work * Time
            j1b1Display1.setText("Power = ");
            j1b1Display2.setText("Work ");
            jtxtX.setText("/");
            j1b1Display3.setText("Time");
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
        else if(jCDistance.getSelectedItem().equals("Momentum"))
        {
            double dst1 = Double.parseDouble(jtxtEnter1.getText());
            double dst2 = Double.parseDouble(jtxtEnter2.getText());
            double dst3;
            //Momentum Formula = Mass * Speed
            j1b1Display1.setText("Momentum = ");
            j1b1Display2.setText("Mass ");
            jtxtX.setText("X");
            j1b1Display3.setText("Speed");
            dst3 = dst1 * dst2;
            String value = String.format("%.2f", dst3);
            j1b1Result.setText(value);
        }
    }//GEN-LAST:event_jbtnconverterActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        this.setResizable(true);
        this.setSize(1100, 600);
        jtxtDisplay.setSize(625, 52);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        
        j1b1Result.setText(null);
        j1b1Display1.setText(null);
        j1b1Display2.setText(null);
        jtxtX.setText(null);
        j1b1Display3.setText(null);
        jtxtEnter1.setText(null);
        jtxtEnter2.setText(null);
        jCDistance.getSelectedItem().equals("Select an option");
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void j1b1Display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1b1Display2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1b1Display2ActionPerformed

    private void jbtncmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncmActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops * 100);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncmActionPerformed

    private void jbtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops/100);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnmActionPerformed

    private void jbtnkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnkgActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops / 1000);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnkgActionPerformed

    private void jbtnlitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlitreActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops / 1000);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnlitreActionPerformed

    private void j2b2ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2b2ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2b2ResultActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        this.setResizable(true);
        this.setSize(1100, 1000);
        jtxtDisplay.setSize(625, 52);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jbtnzakatconverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnzakatconverterActionPerformed
        
        if ((jtxtEnterZ.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"You must enter value to compute",
                    "DST System", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if(jCzakat.getSelectedItem().equals("Net Worth"))
        {
            //Zakat = NetWorth / 40
            double dst1 = Double.parseDouble(jtxtEnterZ.getText());
            double dst2= 40 ;
            double dst3;
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j2b2Result.setText(value);
        }
        
        else if(jCzakat.getSelectedItem().equals("Gold"))
        {
            //Zakat = Gold / 40
            double dst1 = Double.parseDouble(jtxtEnterZ.getText());
            double dst2= 40 ;
            double dst3;
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j2b2Result.setText(value);
        }
        
        else if(jCzakat.getSelectedItem().equals("Silver"))
        {
            //Zakat =  Silver / 40
            double dst1 = Double.parseDouble(jtxtEnterZ.getText());
            double dst2= 40 ;
            double dst3;
            dst3 = dst1 / dst2;
            String value = String.format("%.2f", dst3);
            j2b2Result.setText(value);
        }
    }//GEN-LAST:event_jbtnzakatconverterActionPerformed

    private void jbtnzakatResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnzakatResetActionPerformed
        
        j2b2Result.setText(null);
        jtxtEnterZ.setText(null);
        jCzakat.getSelectedItem().equals("Select an option");
    }//GEN-LAST:event_jbtnzakatResetActionPerformed

    private void jCzakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCzakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCzakatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField j1b1Display1;
    private javax.swing.JTextField j1b1Display2;
    private javax.swing.JTextField j1b1Display3;
    private javax.swing.JTextField j1b1Result;
    private javax.swing.JTextField j2b2Result;
    private javax.swing.JComboBox<String> jCDistance;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jCzakat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnBinary;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCbr;
    private javax.swing.JButton jbtnF;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JButton jbtnV;
    private javax.swing.JButton jbtnbCelsius;
    private javax.swing.JButton jbtncm;
    private javax.swing.JButton jbtncoh;
    private javax.swing.JButton jbtnconverter;
    private javax.swing.JButton jbtncos;
    private javax.swing.JButton jbtndecimal;
    private javax.swing.JButton jbtndivide;
    private javax.swing.JButton jbtnhexa;
    private javax.swing.JButton jbtnisequals;
    private javax.swing.JButton jbtnkg;
    private javax.swing.JButton jbtnlitre;
    private javax.swing.JButton jbtnlnx;
    private javax.swing.JButton jbtnm;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnmod;
    private javax.swing.JButton jbtnmulti;
    private javax.swing.JButton jbtnocta;
    private javax.swing.JButton jbtnpi;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnplusminus;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnround;
    private javax.swing.JButton jbtnsin;
    private javax.swing.JButton jbtnsinh;
    private javax.swing.JButton jbtntan;
    private javax.swing.JButton jbtntanh;
    private javax.swing.JButton jbtnxy;
    private javax.swing.JButton jbtnxy2;
    private javax.swing.JButton jbtnxy3;
    private javax.swing.JButton jbtnzakatReset;
    private javax.swing.JButton jbtnzakatconverter;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtEnter1;
    private javax.swing.JTextField jtxtEnter2;
    private javax.swing.JTextField jtxtEnterZ;
    private javax.swing.JTextField jtxtX;
    // End of variables declaration//GEN-END:variables
}
